### ISSUE TITLE
自编译的openwrt docker镜像无法使用，但是118的可以使用，请问何故？

### ISSUE THREAD

**Issue by soundghost** [ophub/amlogic-s9xxx-armbian#1961]
**Device Information | 设备信息**
 - SOC: S905D
 - Model N1

**Armbian Version | 系统版本**
 - Kernel Version: Linux armbian 6.1.69-ophub
 - Release: bookworm

**Describe the bug | 问题描述**
刷入N1 EMMC后，自己编译了基于immortalwrt编译的固件，又将其转成了docker档案，启动自己的docker镜像后，exec进入容器，修改network后重启网络，只能ping通自己，下载别人的镜像也是同样的故障，后来安装了118的openwrt，exec进入容器修改了ip地址就正常了。

请问该如何使用上自己的镜像文件？

所用命令如下：

```
ip link set eth0 promisc on

docker network create -d macvlan --subnet=192.168.9.0/24 --gateway=192.168.9.1 -o parent=eth0 macnet
```
docker compose 文件内容如下：
```
version: '3.9'
services:
    immortalwrt-n1:
        image: 'immortalwrt-n1:2023.12.21'
        privileged: true
        networks:
            macnet: {}
        container_name: phicomm-n1
        restart: always
networks:
    macnet: {}

```

请不吝赐教，谢谢
